import { Print } from "@mui/icons-material";
import { Button, Typography } from "@mui/material";
import { MutableRefObject, ReactElement, useEffect, useRef, useState } from "react";
import generatePDF, { Margin } from "react-to-pdf";

interface ReportGeneratorProps {
    /**
     * The title for the report generated by this component.
     */
    title: string;
    /**
     * The filename that will be used by the generated pdf.
     */
    filename: string;
    /**
     * All child elements inside the report generator.
     * Only these elements will be visible in the created pdf.
     */
    children: ReactElement | ReactElement[];
    /**
     * Controls if the child elements of this element are displayed
     */
    visible?: boolean;
    /**
     * If true, the given title (passed by the title prop) will only be visible when generating the report.
     */
    titleHidden?: boolean;
    /**
     * A ref to a button element used to trigger generation.
     * If this is null, a button will be added to the top of the element.
     */
    buttonRef?: MutableRefObject<HTMLElement>;
}

/**
 * A component used to generate a PDF of its contents
 */
const ReportGenerator = ({ children, filename, title, visible, titleHidden, buttonRef }: ReportGeneratorProps) => {
    const [isPrint, setIsPrinting] = useState(false);

    // FIXME: this causes the page contents to flash. (specially if visible is false).
    useEffect(() => {
        if (isPrint) {
            // generate the pdf file.
            generatePDF(ref, { filename: filename, page: { margin: Margin.SMALL } })
            setIsPrinting(false);
        }
    }, [isPrint]);

    // handle adding event listeners to custom buttons
    useEffect(() => {
        if (!buttonRef || !buttonRef.current) return;

        const elem = buttonRef.current;
        const handler = () => setIsPrinting(true);
        elem.addEventListener("click", handler);

        return () => elem.removeEventListener("click", handler);

    })

    const ref = useRef<any>();
    return <>
        {buttonRef ? null : <Button onClick={() => setIsPrinting(true)} startIcon={<Print />}>Download</Button>}
        {isPrint || visible ? <div ref={ref} style={{ padding: "4em 2em" }}>
            {isPrint || !titleHidden ? <Typography textAlign="center" variant="h6">{title}</Typography> : null}
            {children}
        </div> : null}
    </>
};


export default ReportGenerator;